### ISSUE TITLE
Async suffix for Task returning methods

### ISSUE THREAD

**Issue by DraxCodes** [anovik/YandexTranslateCSharpSdk#18]
The standard for Task returning methods is to suffix the method name with `Async` as set in Microsoft's Task-based asynchronous pattern (TAP) documentation.

Example: 
https://github.com/anovik/YandexTranslateCSharpSdk/blob/430955968e0bd08ed53bc63491125df1fb2b5c7e/YandexTranslateCSharpSdk/YandexTranslateSdk.cs#L20
```diff
- public async Task<string> DetectLanguage(string text)
+ public async Task<string> DetectLanguageAsync(string text)
```

I'd be happy to help out and go through suffixing the method names if it's something you want to implement. 😃 

Source: https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap

**Comment by anovik** [comment]
@DraxCodes Agree this is a good idea. Could you please proceed?

**Comment by DraxCodes** [comment]
Of-course, I will begin and PR it when done.
